CREATE TABLE pessoa (
  "id" INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "nome" VARCHAR(100) NOT NULL,
  "cpf" VARCHAR(11) NOT NULL UNIQUE,
  "sexo" VARCHAR(10) NOT NULL,
  "nascimento" DATE NOT NULL,
  "profissao" VARCHAR(50) NOT NULL,
  "salario" NUMERIC(7, 3)
);